# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'messagingApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for messagingApp
  pod 'Firebase/Messaging'

  target 'messagingApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'messagingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
